### ISSUE TITLE
how to prepare .pkl file?

### ISSUE THREAD

**Issue by sowmyakavali** [nishchaljs/foot_keypoint_detection#2]
Can you please provide more information about preparing train.pkl file.
If possible update the code or give guidelines to prepare it.

**Comment by nishchaljs** [comment]
> Can you please provide more information about preparing train.pkl file.
> If possible update the code or give guidelines to prepare it.

Hi,
A .pkl file can be generated by using several online Image annotation tools like labelbox. If the annotations are not in .pkl format, then load the annotations in a python dict and store it as .pkl file. An example would be:

import pickle
#write python dict to a file
mydict = {'a': 1, 'b': 2, 'c': 3}
output = open('myfile.pkl', 'wb')
pickle.dump(mydict, output)
output.close()

You can unpack the .pkl file present in the repo, and print it to view the contents of the annotations. If you aim to create your own dataset, then follow the format of the dictionary stored in the .pkl file of this repo to use the repo's training code.
